### ISSUE TITLE
np.matrix is not supported. 

### ISSUE THREAD

**Issue by ruqianl** [ElementoLab/utag#6] opened 2023-01-09 01:33 UTC
Hi,

I have been trying to apply utag on my dataset, but has come across the error as below and not sure how to fix it. And I was wondering if you have any ideas of which part of the data should be converted to np.asarray.

Thanks very much!

```
File conda_envs/utag/lib/python3.8/site-packages/utag/segmentation.py:141, in utag(adata, channels_to_use, slide_key, save_key, filter_by_variance, max_dist, normalization_mode, keep_spatial_connectivity, pca_kwargs, apply_umap, umap_kwargs, apply_clustering, clustering_method, resolutions, leiden_kwargs, parc_kwargs, parallel, processes)
137 if slide_key:
  138     ads = [
    139         ad[ad.obs[slide_key] == slide].copy() for slide in ad.obs[slide_key].unique()
    140     ]
--> 141     ad_list = parmap.map(
  142         _parallel_message_pass,
  143         ads,
  144         radius=max_dist,
  145         coord_type="generic",
  146         set_diag=True,
  147         mode=normalization_mode,
  148         pm_pbar=True,
  149         pm_parallel=parallel,
  150         pm_processes=processes,
  151     )
152     ad_result = anndata.concat(ad_list)
153     if keep_spatial_connectivity:
  
  File conda_envs/utag/lib/python3.8/site-packages/parmap/parmap.py:296, in map(function, iterable, *args, **kwargs)
279 def map(function, iterable, *args, **kwargs):
  280     """This function is equivalent to:
    281         >>> [function(x, args[0], args[1],...) for x in iterable]
    282 
   (...)
    294        :type pm_pbar: bool or dict
    295     """
--> 296     return _map_or_starmap(function, iterable, args, kwargs, "map")

File conda_envs/utag/lib/python3.8/site-packages/parmap/parmap.py:226, in _map_or_starmap(function, iterable, args, kwargs, map_or_starmap)
224 # Handle case: Execute sequentially:
225 if not parallel:
  --> 226     return _serial_map_or_starmap(function, iterable, args, kwargs,
                                            227                                   progress, map_or_starmap)
228 func_star = _get_helper_func(map_or_starmap)
229 # Handle case: Without showing progress bar

File conda_envs/utag/lib/python3.8/site-packages/parmap/parmap.py:162, in _serial_map_or_starmap(function, iterable, args, kwargs, progress, map_or_starmap)
160     iterable = tqdm.tqdm(iterable, **tqdm_options)
161 if map_or_starmap == "map":
  --> 162     output = [function(*([item] + list(args)), **kwargs)
    163               for item in iterable]
164 elif map_or_starmap == "starmap":
  165     output = [function(*(list(item) + list(args)), **kwargs)
    166               for item in iterable]

File conda_envs/utag/lib/python3.8/site-packages/parmap/parmap.py:162, in <listcomp>(.0)
160     iterable = tqdm.tqdm(iterable, **tqdm_options)
161 if map_or_starmap == "map":
  --> 162     output = [function(*([item] + list(args)), **kwargs)
    163               for item in iterable]
164 elif map_or_starmap == "starmap":
  165     output = [function(*(list(item) + list(args)), **kwargs)
    166               for item in iterable]

File conda_envs/utag/lib/python3.8/site-packages/utag/segmentation.py:228, in _parallel_message_pass(ad, radius, coord_type, set_diag, mode)
220 def _parallel_message_pass(
  221     ad: AnnData,
  222     radius: int,
  (...)
  225     mode: str,
  226 ):
  227     sq.gr.spatial_neighbors(ad, radius=radius, coord_type=coord_type, set_diag=set_diag)
--> 228     ad = custom_message_passing(ad, mode=mode)
229     return ad

File conda_envs/utag/lib/python3.8/site-packages/utag/segmentation.py:241, in custom_message_passing(adata, mode)
237     A_mod = A + np.eye(A.shape[0])
239     from sklearn.preprocessing import normalize
--> 241     affinity = normalize(A_mod, axis=1, norm="l1")
242 else:
  243     # Plain A_mod multiplication
244     A = adata.obsp["spatial_connectivities"]

File conda_envs/utag/lib/python3.8/site-packages/sklearn/preprocessing/_data.py:1817, in normalize(X, norm, axis, copy, return_norm)
1814 else:
  1815     raise ValueError("'%d' is not a supported axis" % axis)
-> 1817 X = check_array(
  1818     X,
  1819     accept_sparse=sparse_format,
  1820     copy=copy,
  1821     estimator="the normalize function",
  1822     dtype=FLOAT_DTYPES,
  1823 )
1824 if axis == 0:
  1825     X = X.T

File conda_envs/utag/lib/python3.8/site-packages/sklearn/utils/validation.py:737, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator, input_name)
646 """Input validation on an array, list, sparse matrix or similar.
    647 
    648 By default, the input is checked to be a non-empty 2D array containing
   (...)
    734     The converted and validated array.
    735 """
736 if isinstance(array, np.matrix):
  --> 737     raise TypeError(
    738         "np.matrix is not supported. Please convert to a numpy array with "
    739         "np.asarray. For more information see: "
    740         "https://numpy.org/doc/stable/reference/generated/numpy.matrix.html"
    741     )
743 xp, is_array_api = get_namespace(array)
745 # store reference to original array to check if copy is needed when
746 # function returns

TypeError: np.matrix is not supported. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
```

**Comment by jkim810** [comment] 2023-01-26 17:03
Hello!

Sorry for the late follow up. Based on the error message, it seems like the `X` attribute of `anndata` (`anndata.X`) is set an `np.matrix` and needs to be updated as an `np.asarray`. In the meantime, I would also encourage setting `anndata.obsm['spatial']` as an `np.array` with a `dtype` of `float` or `int`.

**Comment by ruqianl** [comment] 2023-02-03 03:50
Hi @jkim810 ,

Thanks for your reply! I set the X to be np.asarry but the same error would pop up. I checked the code a bit further, it seems the error was raised from line 241:

    235    if mode == "l1_norm":
    236         A = adata.obsp["spatial_connectivities"]
    237         A_mod = A + np.eye(A.shape[0])
    238
    239         from sklearn.preprocessing import normalize
    240
    241         affinity = normalize(A_mod, axis=1, norm="l1")**
    242     else:
    243         # Plain A_mod multiplication
    244         A = adata.obsp["spatial_connectivities"]
    245         affinity = A

The function would work if changing the mode to "l2_norm".

**Comment by vipulsinghal02** [comment] 2023-02-15 17:13
Hi, I would like to second this question. I was trying to run the UTAG tutorial, but also run into the same error. Seems like both `adata.X` and `anndata.obsm['spatial']` are of the correct types: 

`print(type(adata.obsm['spatial']))
print(adata.obsm['spatial'].dtype)
float64`

**Comment by vipulsinghal02** [comment] 2023-02-15 18:21
Figured out what the issue is. Here: 

236         A = adata.obsp["spatial_connectivities"]
237         A_mod = A + np.eye(A.shape[0])

you are adding A, which is of type `scipy.sparse._csr.csr_matrix` to np.eye, which is of class `numpy.ndarray`. 

The resulting class of A_mod is `<class 'numpy.matrix'>`, which causes `check_array` inside sklearn's `normalize` function to spit out the error above. Changing the normalization method to anything but `l1_norm` bypasses the problematic line 237, but that just pushes the problem under the rug / does not run UTAG under its specified defaults. 

@jkim810 Looking forward to a fix! :-)

**Comment by jkim810** [comment] 2023-02-16 04:38
Hello @ruqianl and @vipulsinghal02.

Thanks for the detailed bug report. I think there was an update in dependencies that caused the issue. The type error is now fixed. Please let me know if you encounter any other issues along the way.

**Comment by vipulsinghal02** [comment] 2023-02-16 04:44
Wonderful! Will test it out soon and let you know if I run into any other issues. 

Cheers, 
Vipul

**Comment by vipulsinghal02** [comment] 2023-02-16 05:17
@jkim810 It works now, thank you. You may close this issue. 

Cheers

**Closed** 2023-02-16 12:06 UTC
